config/routes.rb
Rails.application.routes.draw do
  root"static_pages#home" 
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/user_policy', to: 'static_pages#user_policy', as: 'user_policy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get "/auth/failure" => "sessions#failure"
  delete '/logout',  to: 'sessions#destroy'
  delete '/resign/:id', to: 'users#resign', as: 'resign'
  get '/search', to: 'posts#search', as: 'search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  get '/users/:id/password', to: 'users#edit_password', as: 'edit_password'
  patch '/users/:id/password', to: 'users#update_password', as: 'password'
  resources :posts,          only: [:show, :new, :create, :destroy] do
    post '/add', to: 'favorites#create'
    delete '/add', to: 'favorites#destroy'
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :comments
  has_many :favorites
  has_many :fav_posts, through: :favorites, source: :post
  before_save   :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  validates :user_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }, allow_blank: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates_acceptance_of :agreement, allow_nil: false, message: "が必要です", on: :create 
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 試作feedの定義
  # 完全な実装は次章の「ユーザーをフォローする」を参照
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})", user_id: id)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  def like(post)
    favorites.find_or_create_by(post_id: post.id)
  end
  
  def unlike(post)
    favorite = favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end
  
  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase if self.email
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update,
                                :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録が完了しました！"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "編集が完了しました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを消去しました"
    redirect_to users_url
  end
  
  def resign
    User.find(params[:id]).destroy
    flash[:success] = "退会しました"
    redirect_to root_path
  end
  
  def edit_password
    @user = User.find(params[:id])
  end
  
  def update_password
    @user = User.find(params[:id])
    if params[:user][:new_password].empty?
      flash[:danger] = "新しいパスワードを入力してください"
      render 'edit_password'
    elsif @user.authenticate(params[:user][:password]) && 
          params[:user][:new_password] == params[:user][:new_password_confirmation]
      @user.update_attributes(password: params[:new_password],
            password_confirmation: params[:new_password_confirmation])
      flash[:success] = "パスワードを変更しました！"
      redirect_to @user
    else
      flash[:danger] = "パスワードが正しくありません" unless  @user.authenticate(params[:user][:password]) 
      flash[:danger] = "新しいパスワードは同じ内容を入力してください" unless
            params[:user][:new_password] == params[:user][:new_password_confirmation]
      render 'edit_password'
    end
  end
  
  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :user_name, :password,
            :password_confirmation, :agreement, :email, :provider, :uid,
            :website, :introduce, :phone_number, :gender)
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
 # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase) if user.email
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "消去", user, method: :delete,
                                  data: { confirm: "消去しますか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <p>ーーーーーーーーーーーーーーー公開情報ーーーーーーーーーーーーーーーーーー</p>
      <%= f.label :name %>【必須】
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :user_name %>【必須】
      <%= f.text_field :user_name, class: 'form-control' %>

      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>

      <%= f.label :introduce %>
      <%= f.text_area :introduce, :size=>"60x10", class: 'form-control' %>
      <p>ーーーーーーーーーーーーーーー非公開情報ーーーーーーーーーーーーーーーーー</p>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <div class="form-group row">
        <div class="col-sm-2">
          <%= f.label :gender, {class: 'form-label'} %>
        </div>
        <div class="col-sm-10 btn-group" data-toggle="buttons">
          <label class="btn btn-outline-secondary active" style="width:50%">
            <%= f.radio_button :gender, 0, {checked: true} %> 男性
          </label>
          <label class="btn btn-outline-secondary" style="width:50%">
            <%= f.radio_button :gender, 1, {} %> 女性
          </label>
        </div>
      </div>
      
      <%= f.submit "保存", class: "btn btn-primary" %>
    <% end %>
    <p>ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー</p>
    <div class="right">
      <label>|<%= link_to "アカウント消去", resign_path(@user), method: :delete,data: { confirm: "消去しますか？" }%></label>
      <label>|<%= link_to "パスワード変更", edit_password_path(@user) %></label>
      <label><%= link_to "プロフィール写真変更", "http://gravatar.com/emails", target: "_blank" %></label>
    </div>
    <%= gravatar_for @user %>
    <p>ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー</p>
  </div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, 'パスワード変更') %>
<h1>パスワード変更</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :new_password %>
      <%= f.password_field :new_password, class: 'form-control' %>

      <%= f.label :new_password_confirmation %>
      <%= f.password_field :new_password_confirmation, class: 'form-control' %>

      <%= f.submit "パスワード変更", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.hidden_field :provider, :value => session[:provider] %>
      <%= f.hidden_field :uid, :value => session[:uid] %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <div class="checkbox">
        <label>
          <%= f.check_box :agreement, as: :boolean, checked:false %>
          <%= link_to("利用規約", user_policy_path) %>に同意する
        </label>
      </div>
      
      <%= f.submit "登録する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="show_info">
      <h1><%= gravatar_for @user %></h1>
      <div class= "name"><%= @user.name %></div>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <div class="introduce">
        <% if @user.introduce %>
          <h1>自己紹介</h1>
          <h1 class="text"><%= @user.introduce %></h1>
        <% else %>
          <h1 class="text">自己紹介文はまだありません</h1>
        <% end %>
      </div>
    </section>
    <%= link_to "プロフィール編集", edit_user_path(current_user) if @user == current_user%>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.posts.any? %>
      <h3>投稿数(<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <% @posts.each do |post| %>
        <div id="grid", class="picture">
          <ul>
            <li id="post-<%= post.id %>">
                <%= link_to post do %>
                  <%= image_tag post.picture.url, width: "200", height: "200" if post.picture? %>
                <% end %>
            </li>
          </ul>
        </div>
        <% end %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィール", @user %></span>
      <span><b>投稿数:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>