config/routes.rb
Rails.application.routes.draw do
  root"static_pages#home" 
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/user_policy', to: 'static_pages#user_policy', as: 'user_policy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get "/auth/failure" => "sessions#failure"
  delete '/logout',  to: 'sessions#destroy'
  delete '/resign/:id', to: 'users#resign', as: 'resign'
  get '/search', to: 'posts#search', as: 'search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  get '/users/:id/password', to: 'users#edit_password', as: 'edit_password'
  patch '/users/:id/password', to: 'users#update_password', as: 'password'
  resources :posts,          only: [:show, :new, :create, :destroy] do
    post '/add', to: 'favorites#create'
    delete '/add', to: 'favorites#destroy'
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_comment_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "コメントを入力してください..." %>
  </div>
  <%= f.submit "コメントする", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>箇所のエラーがあります
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<div class = "gravatar">
  <%= link_to gravatar_for(current_user, size: 50), current_user %>
</div>
<h1><%= current_user.name %></h1>
<span><%= link_to "マイページ", current_user %></span>
<span>投稿数：<%= current_user.posts.count %></span>