config/routes.rb
Rails.application.routes.draw do
  root"static_pages#home" 
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/user_policy', to: 'static_pages#user_policy', as: 'user_policy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get "/auth/failure" => "sessions#failure"
  delete '/logout',  to: 'sessions#destroy'
  delete '/resign/:id', to: 'users#resign', as: 'resign'
  get '/search', to: 'posts#search', as: 'search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  get '/users/:id/password', to: 'users#edit_password', as: 'edit_password'
  patch '/users/:id/password', to: 'users#update_password', as: 'password'
  resources :posts,          only: [:show, :new, :create, :destroy] do
    post '/add', to: 'favorites#create'
    delete '/add', to: 'favorites#destroy'
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :users, through: :favorites
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :picture, presence: true
  validates :picture_title, length: { maximum: 140 }
  validate  :picture_size
  
  def self.search(search)
    return Post.all unless search
    Post.where(['picture_title LIKE ?', "%#{search}%"])
  end
    
  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "は５MB以下でアップロードしてください")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user,   only: :destroy

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments.paginate(page: params[:page])
    @comment = Comment.new
  end

  def new
    @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "画像をアップロードしました！"
      redirect_to @post
    else
      @feed_items = []
      render 'new'
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = "画像を消去しました！"
    redirect_to request.referrer || root_url
  end
  
  def search
    @posts = Post.search(params[:search])
  end
  
  private

    def post_params
      params.require(:post).permit(:picture_title, :picture)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="picture_title">
    <%= post.picture_title if post.picture_title %>
  </span>
  <span class="picture">
    <%= link_to post do %>
      <%= image_tag post.picture.url if post.picture? %>
    <% end %>
  </span>
  <span class="timestamp">
    <%= time_ago_in_words(post.created_at) %>前
    <% if !Favorite.exists?(user_id: current_user.id, post_id: post.id) %>
      <%= link_to "お気に入り登録", post_add_path(post), method: :post %>
    <% else %>
      <%= link_to "お気に入り解除", post_add_path(post), method: :delete %>
    <% end %>
  </span>
</li>

app/views/posts/new.html.erb
<% provide(:title, '画像アップロード') %>
<h1>画像アップロード</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :picture_title %>
        <%= f.text_area :picture_title %>
      </div>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.submit "アップロード", class: "btn btn-primary" %>
    <% end %>
    
    <script type="text/javascript">
      $('#post_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
          alert('ファイルサイズを5MB以下にしてください');
        }
      });
</script>
  </div>
</div>

app/views/posts/search.html.erb
<% provide(:title, '検索') %>
<h1>検索</h1>

<%= form_tag(search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil %>
<% end %>
  
<div class="posts">
  <%= render @posts%>
</div>

app/views/posts/show.html.erb
<% provide(:title, " 投稿写真") %>
<div class="row">
  <aside class="col-md-4">
    <section class="comment_form">
        <%= render 'shared/comment_form' %>
    </section>
  </aside>
  <div class="col-md-8 posts_show" >
    <section class="user_info">
      <h1><%= gravatar_for @user %></h1>
      <h1><%= @user.name %></h1>
    </section>
    <%= image_tag @post.picture.url, width: "400", height: "400" %>
    <div class="fovorite">
      <% if !Favorite.exists?(user_id: current_user.id, post_id: @post.id) && @post.user != current_user %>
        <%= link_to "お気に入り登録", post_add_path(@post), method: :post %>
      <% elsif @post.user != current_user %>
        <%= link_to "お気に入り解除", post_add_path(@post), method: :delete %>
      <% end %>
    </div>
    <% if @post.comments.any? %>
      <h3>コメント数(<%= @post.comments.count %>)</h3>
      <ol class="comments">
          <%= render @comments %>
      </ol>
      <%= will_paginate @comments %>
    <% end %>
  </div>
</div>